project:
  type: website

website:
  title: "To Vanessa, Happy Birthday Baby Girl"
  favicon: images/logo.png
  page-navigation: true
  site-url: https://michaelgicheru.github.io/vanessa-dashboard
  repo-url: https://github.com/michaelgicheru/vanessa-dashboard
  repo-actions: [edit, source, issue]
  sidebar:
    title: "To Vanessa:"
    style: "docked"
    search: true
    collapse-level: 1
    logo: images/logo.png
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Playlist

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: atom-one-dark
    toc: true
    grid:
      sidebar-width: 150px