---
title: "Birthday Card"
---

Happy Birthday Vanessa. I am so glad I could spend another year around the sun with you. I know this is coming to you six months later that promised but hey, better late than never!! There is so much I want to tell you like how much I admire your honesty and your dedication to God and how beautiful you are to me. Words are not enough to express how much I love and admire you, like seriously, I don't think I can describe it adequately. And well I thought, I will try with the next best thing, _drumrolls please_, music!!. SO here goes baby girl, these are the songs that remind me of you:

1. Call Me Lover: "I love it when you call me lover". I love it when you tell me that you love me. I kid you not, my head plays this song every time you love me.

2. Acid eyes. "I never told you loved you, when I looked into your acid eyes". Well this song is more of the opposite of what I feel. I'm so glad I told you that I loved you and continue to do so even now. I might add though, I don't know what acid eyes are.

3. Tek it. This song reminds me of the floaty feeling you give me whenever we are together. "I watch the moon. Let it run my mood. Can't stop thinking about you." The melody is very tiktoky but I love it weirdly 😂. And again it's the floaty feeling for me.

4. Spice. "Spice up your life. Who would want anything else". I'm in my 20s now and I'm so glad it has some spice in the form of you. This song makes me want to travel around with you, try new things, conquer the world even. You always make me feel like I am on the verge of discovering and experiencing something new whenever I am with you.

5. Lunch. "I could eat that girl for lunch." The first sexual song on this playlist! The entire chorus reminds me of the other side of the feelings I have for you, the attraction I have for you. You taste like the one for me. I could buy you so much stuff. It's a craving not a crush. I would absolutely love to eat you for lunch. You need a seat I definitely volunteer. Also I kinda love the piano on the chorus. Billie Eilish ate with this one, no notes. 

6. Pretty boy. "Even if my hearts stop beating, you are the only thing I need" this line definitely speaks for itself. "As long as I got you, I'm gonna be alright ". I genuinely feel like I could do anything or be anyone with you baby girl.

7. Big. My man made sunshine. I bought the sweater because of this song and artist btw, aside from it looking pretty cool. This song reminds me of the floaty and(!) homey feeling you give me when I'm with you. Of an afternoon at home with it raining outside with soft music playing in the background.

8. Yahweh Elyon. Thank you for sharing this song with me Vanessa. You are literally a God send to my life. I pry you will continue to be one of God's greatest soldiers.

9. Sorry. I have a pretty love hate relationship with this song. On one hand,it's hands down one of the best songs I've ever heard but at the same time it reminds me a lot of the times I've let you down. "I'm sorry, so sorry, for all I've done." I hope you'll always remember this line when I disappoint you, cause I never intentionally want to. (Not like I'm planning to disappoint you or anything)

10. Happier than ever. You love this song. Or at least, I hear you singing it sometimes😂.

11. Rock your body. "I wanna rock your body...dance with me". I want to dance to this song with you😤. (Update: it's going to the playlist when we are dancing in our wedding 😂)

12. Matthew 6. "But Jesus and His will remain". This serves a reminder to me of God's love and will for his children. I added it in there cause above all else even my love for you is waning compared to what God's love for you is and what His will for you is.

I hope you love the playlist and the headphones especially!! (Those were supposed to be a surprise to you together with this website as well) I've gotten into an artist called Sam fender lately, I like his style. Two of his songs feature on this playlist. There's another song of his called "Will we talk?" You should listen to it: "She said, if you dance with me darling, if you take me home? Will we talk in the morning?" This line makes me want to take me home with you and dance with you.

I leave you with this admittedly pretty famous verse:

> Mathew 6:33-34: 
But seek first his kingdom and his righteousness, and all these things will be given to you as well. Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.

Be patient and trust in God in all that you do Vanessa

**You will always be my man-made sunshine**